### ISSUE TITLE
Capability type is too restrictive

### ISSUE THREAD

**Issue by Gozala** [ucan-wg/ts-ucan#16]
Current definition of capability is too restrictive

https://github.com/fission-suite/ucan/blob/bfbdbdac3cd7cd58d0382c683d2843a536e1eb9d/src/types.ts#L24-L27

Specifically by demanding all values to be strings it makes it inconvenient to capture numeric restrictions like upload quota, or number of uploads etc..

It is possible to encode those as strings, however it probably makes more sense to loosen that restriction.

**Comment by expede** [comment]
Agreed 💯
