### ISSUE TITLE
Support redelegation capability

### ISSUE THREAD

**Issue by matheus23** [ucan-wg/ts-ucan#43]
The spec mentions a `"*"` resource: https://whitepaper.fission.codes/access-control/ucan/jwt-authentication#resource-identifier

> Delegate all resources of any type that are in scope

Fission will need that to be implemented for device linking.

We need to add some logic to parsing & capability checking to support this. In capability checking it essentially allows you to "forward" who the "originator" is for all capabilities without having to mention concrete capabilities.

**Comment by expede** [comment]
Updated per UCAN 0.8:

* https://github.com/ucan-wg/spec#41-all-owned-resources
* https://github.com/ucan-wg/spec#421-prf-scheme

**Comment by icidasset** [comment]
@matheus23 I think this partially implemented with my last PR? It's got some utility functions for creating `prf` capabilities and for superuser `*` resources/abilities.

Not sure what else is needed, or what you mean exactly with:
> In capability checking it essentially allows you to "forward" who the "originator" is for all capabilities without having to mention concrete capabilities.

Can you clarify? 🙏
