### ISSUE TITLE
Validation should compare that root "iss" matches outermost "aud"

### ISSUE THREAD

**Issue by Gozala** [ucan-wg/ts-ucan#49]
In my first prototype with UCANs I've made a mistake of not creating nor validating that outermost UCAN was issued for the service receiving a request. I think that is fairly easy mistake given how conventional token systems work on the web.

I think it would make a lot more sense if validation step checked that proof chain makes the full loop & maybe optionally allowed providing alternative "key" to compare outmost "aud" in case service is providing service on others behalf.

**Comment by Gozala** [comment]
P.S.: My colleague made exact same mistake recently, which is to further support the claim that this mistake is easy to make.

**Comment by expede** [comment]
Fixed by https://github.com/ucan-wg/spec/pull/20
