### ISSUE TITLE
`rootIssuer` method

### ISSUE THREAD

**Issue by nichoth** [ucan-wg/ts-ucan#55]
Another bit of knowledge I wanted to document -- the `rootIssuer` method

This was removed because multiple roots are possible, I think:
https://github.com/ucan-wg/ts-ucan/pull/24

I had used `rootIssuer` here in the past in the demo app:
https://github.com/nichoth/ucan-demo/blob/f63365fb4039b5d922eee46c02d1b69609bab31b/src/index.js#L297

This is for a use case where all UCANs are descended from a single keypair that is unique to the server. I'm not sure if that is a use case that should be supported. You check that the chain of UCANs is valid, and also check that the rootIssuer is the server's ID.

Is there a plan to provide for something equivalent in the future? Or is this best left to user-land to implement? 

I actually attempted to implement here -- https://github.com/nichoth/ucan-demo/blob/better-validation/src/index.js#L314 -- but as far as I made it was getting an error in the `decode` function:
```
SyntaxError: Non-base64url character
```

**Comment by matheus23** [comment]
> This was removed because multiple roots are possible

This is correct! UCANs can now include multiple proofs - changing it from chains of UCANs to trees of UCANs. Thus, the rootIssuer can't be identified for UCANs as a whole.

> This is for a use case where all UCANs are descended from a single keypair that is unique to the server. I'm not sure if that is a use case that should be supported.

That is absolutely a use-case that should be supported.

> Is there a plan to provide for something equivalent in the future? Or is this best left to user-land to implement?

What you could do with the new UCAN version is to introduce an "invite" capability. This capability is passed on through your UCAN chain. Then finally you can check that the UCAN is a valid invite using `hasCapability` & providing the time you're checking the invite for and the server's DID as originator (the equivalent of rootIssuer - but for capabilities).

**Comment by nichoth** [comment]
>  introduce an "invite" capability

I like that. It makes sense in the UCAN view of the world.

I think I see; the `hasCapability` function takes an object `capabilityWithInfo`, that includes a property `info.originator`. And you would want to pass in the server's DID there.
