### ISSUE TITLE
Leveraging WebAssembly?

### ISSUE THREAD

**Issue by dOrgJelli** [ucan-wg/ts-ucan#85]
What have been the ucan-wg's thoughts on leveraging WebAssembly? I'd imagine it could help:
- Reduce code duplication in the various implementations that exist today.
- Allow for dynamic user-defined logic to be built into the protocol, making it more future proof.

Disclaimer - I work on the Polywrap project, a WebAssembly toolchain + runtime that could offer a solution here https://polywrap.io/

**Comment by bmann** [comment]
There is rs-UCAN by @cdata https://github.com/cdata/rs-ucan

Fission is slowly WASM-ifying things across the related codebase we work on. So yes, we agree ;)

**Comment by bmann** [comment]
Also going to close this — come join the WG spec discussion forum, that’s a better place for this discussion. Would you mind reposting there? https://github.com/ucan-wg/spec/discussions

**Comment by expede** [comment]
@dOrgJelli just to expand on Boris' comments above: this is something we've been exploring in some detail. rs-ucan targeting both native and Wasm and writing wrappers for various languages seems like a good idea, but we haven't put this into practice yet. It would certainly be more efficient for maintainers!

**Comment by expede** [comment]
Moved further discussion here: https://github.com/ucan-wg/spec/discussions/84
