### ISSUE TITLE
Lock uint8arrays at 3.0.0

### ISSUE THREAD

**Issue by dholms** [ucan-wg/ts-ucan#87]
Uint8Arrays version 3.1.0 included a [breaking change](https://github.com/achingbrain/uint8arrays/issues/38).

When `Buffer` is available (for instance in Node), it will return Buffers instead of Uint8Arrays.

The WebCrypto API expects Uint8Arrays or ArrayBuffers and does not work as expected with Buffers.

We need to lock `uint8arrays` at 3.0.0 or wrap the library & convert all Buffers to Uint8Arrays.

**Comment by matheus23** [comment]
> When `Buffer` is available (for instance in Node), it will return Buffers instead of Uint8Arrays.

:(

Alright. Let's do the locking :)

**Comment by tennox** [comment]
uint8arrays has been fixed: https://github.com/achingbrain/uint8arrays/pull/39

Can you upgrade? My problem is that `uint8arrays@3` depends on old version of `multiformats`, which does not work in browsers easily (requires those nasty polyfills)...
