### ISSUE TITLE
Release please?

### ISSUE THREAD

**Issue by achingbrain** [ucan-wg/ts-ucan#93]
Is https://github.com/ucan-wg/ts-ucan/pull/92 going to make it into a release soon?

The current version of `ucans` on npm (0.10.0 at the time of writing) can't be used with node in ESM mode without this fix.

**Comment by matheus23** [comment]
Yeah, this is confusing. We have `@ucans/core` and `@ucans/default-plugins` on the newer versions, but `@ucans/ucans` is still on version `0.11.0` (not `0.11.2`) and `ucans` still exists.

IIRC, deleting packages on NPM is quite hard, so I don't think we can do much about `ucans`.

For `@ucans/ucans`, @dholms can you publish the current version of `@ucans/ucans`, so it's now 0.11.2? Or can you tell me how you usually do that? I tried `yarn publish`, but that fails with `error Couldn't publish package: "https://registry.yarnpkg.com/@ucans%2fcore: Not found"`, and I tried `npm publish`, which fails with `Not Found - PUT https://registry.npmjs.org/@ucans%2fucans - Not found`. And ideas?

**Comment by achingbrain** [comment]
Ah, ok - are people supposed to use `@ucans/ucans` instead of `ucans`?  I missed that, probably because the README examples [import from `ucans`](https://github.com/ucan-wg/ts-ucan#example).

> IIRC, deleting packages on NPM is quite hard, so I don't think we can do much about ucans.

You can [deprecate](https://docs.npmjs.com/cli/v9/commands/npm-deprecate) the package with a message that says something like `"This module is deprecated, please use @ucans/ucans instead"` - that'd appear on the README on npm and also in the console when someone installs `ucans`.

**Comment by matheus23** [comment]
Haha yeah. Fair enough!
We'd appreciate a README PR :pray: 
Thanks for the deprecation pointer, I'll look into that.

Also, would love to talk to you in general about UCAN & what you're up to (which I'm guessing is helia?).
Please come by to the UCAN discord (https://ucan.xyz/community/) or let me know some other way of talking to you :)

**Comment by matheus23** [comment]
While we're at it, we should probably also publish the readme to `@ucans/ucans`. Currently it lives only on the top level...

FWIW, I've deprecated `ucans` for now.

**Comment by bmann** [comment]
@achingbrain a lot of our new stuff is using rs-ucan https://github.com/ucan-wg/rs-ucan - turned into Wasm for Web deployment. 

I also started a thread about WNFS https://github.com/wnfs-wg/spec/discussions/55

Happy to have a sync session with you about all these topics. Let us know how we can support you!

**Comment by Frando** [comment]
Hello, could you please release `@ucans/ucans` v0.11.2?

My PR #92 was merged quite a while back to fix failing ESM imports, and we're actively using this in [repco](https://github.com/openaudiosearch/repco-specs), and I'd love to get rid of the dependency on my fork (and would like to avoid republishing). Thanks!

**Comment by bmann** [comment]
Hey @Frando thats awesome to hear you’re actively using it. Have you introduced yourself / your project in the discussion forum? https://github.com/ucan-wg/spec/discussions

Would be great to get you listed on the website too. 

And: we’d love to add maintainers to this repo. Are you interested?

**Comment by icidasset** [comment]
Released https://www.npmjs.com/package/@ucans/ucans/v/0.11.2

**Comment by Frando** [comment]
@bmann I forgot to come back to you! Yup, I'll do an intro in the forum, haven't noticed the discussion yet. I could do some light co-maintenance, however we're also looking into the UCAN libraries by DAG house currently, and haven't settled yet where we'll go in the next iteration of [repco](https://github.com/openaudiosearch/repco).

**Comment by bmann** [comment]
Great and thanks for the link to what you’re working on.
