### ISSUE TITLE
encode + parse

### ISSUE THREAD

**Issue by nichoth** [ucan-wg/ts-ucan#98]
In [packages/core/src/token.ts](https://github.com/ucan-wg/ts-ucan/blob/main/packages/core/src/token.ts#L238), we have this parse function, that throws an error `Expected JWT format: 3 dot-separated base64url-encoded values`:

```ts
export function parse(encodedUcan: string): UcanParts {
  const [ encodedHeader, encodedPayload, signature ] = encodedUcan.split(".")

  if (encodedHeader == null || encodedPayload == null || signature == null) {
    throw new Error(`Can't parse UCAN: ${encodedUcan}: Expected JWT format: 3 dot-separated base64url-encoded values.`)
  }
```

But in `encode.ts`, we have this [encode function](https://github.com/ucan-wg/ts-ucan/blob/main/packages/core/src/token.ts#L187), that returns two dot separated segments:
```js
/**
 * Encode a UCAN.
 *
 * @param ucan The UCAN to encode
 */
export function encode(ucan: Ucan<unknown>): string { 
  return `${ucan.signedData}.${ucan.signature}`
}
```

---------------------------------------------------------------

Does the parse function need updating? (`yarn run test` failed on my machine)

**Comment by matheus23** [comment]
It shouldn't fail because of that. `ucan.signedData` is initialized to a string containing a dot:
https://github.com/ucan-wg/ts-ucan/blob/6fad15027523846a2a427ed2e74f34a699cfd79d/packages/core/src/token.ts#L148

**Comment by nichoth** [comment]
> What's the error you get when you yarn run test?

```
ts-ucan main % yarn run test
PASS tests/semver.test.ts
PASS tests/capability.test.ts

Test Suites: 2 passed, 2 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        0.587 s, estimated 1 s
Ran all test suites.
FAIL tests/ed25519.test.ts
  ● Test suite failed to run

    src/ed25519/plugin.ts:1:30 - error TS2307: Cannot find module '@ucans/core' or its corresponding type declarations.

    1 import { DidKeyPlugin } from "@ucans/core"
                                   ~~~~~~~~~~~~~

FAIL tests/ecdsa.test.ts
  ● Test suite failed to run

    src/p256/plugin.ts:1:30 - error TS2307: Cannot find module '@ucans/core' or its corresponding type declarations.

    1 import { DidKeyPlugin } from "@ucans/core"
                                   ~~~~~~~~~~~~~

FAIL tests/rsa.test.ts
  ● Test suite failed to run

    src/rsa/plugin.ts:1:30 - error TS2307: Cannot find module '@ucans/core' or its corresponding type declarations.

    1 import { DidKeyPlugin } from "@ucans/core"
                                   ~~~~~~~~~~~~~

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        1.481 s
Ran all test suites.
error Command failed with exit code 1.                                         
error Command failed.                                                          
Exit code: 1
Command: /usr/local/bin/node
Arguments: /Users/nick/.node/corepack/yarn/1.22.15/lib/cli.js test
Directory: /Users/nick/code/ts-ucan/packages/default-plugins
Output:

error Command failed with exit code 1.
```

**Comment by nichoth** [comment]
> `ucan.signedData` is initialized to a string containing a dot

That's actually my confusion here. It is a string containing a single dot, but the error message says

> 3 dot-separated base64url-encoded values

**Comment by nichoth** [comment]
For the tests, you must do `npm run build` (or `yarn run build`) first, so never mind about that; they passed for me.

**Comment by matheus23** [comment]
> > `ucan.signedData` is initialized to a string containing a dot
> 
> That's actually my confusion here. It is a string containing a single dot, but the error message says
> 
> > 3 dot-separated base64url-encoded values

Read over my messages and the code above again :) : `ucan.signedData` contains a dot, and finally it gets combined with a dot and `ucan.signature`, which gives you a three-dots string.

**Comment by nichoth** [comment]
Got it thanks!
